# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: server-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       component: server
#   template:
#     metadata:
#       labels:
#         component: server
#     spec:
#       containers:
#         - name: server
#           image: jgddocker/multi-server
#           ports:
#           - containerPort: 5000

# WE CAN COMBINE MORE THAN ONE K8S-SETUP YAML FILES WITH A SPLIT OF '---' BETWEEN DIFFERENT CONFIGURATIONS
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: server-cluster-ip-service
# spec:
#   type: ClusterIP
#   selector:
#     component: server
#   ports:
#     - port: 5000
#       targetPort: 5000
